= SpeakCoding API
:toc:

SpeakCoding API conforms to https://jsonapi.org/[JSON:API] standard.

== Authentication

Clients get authentication token in response to <<Create User>> and <<Authenticate User>> requests. They MUST include this token with all requests to the API by using `Authentication-Token` header.

== Requests

=== Create User

`POST /users.json`

Client MUST NOT be authenticated.

Parameters: all <<User>> data type parameters and additional `password` parameter for password. Namespaced with `user`.

*Response*

<<User>> structure. Meta contains `authentication_token` to use for authentication.

=== Authenticate User

`POST /users/authenticate.json`

Client MUST NOT be authenticated.

Parameters: `user[email]` and `user[password]`.

*Response*

Same as for <<Create user>>, but for given user.

=== Update User

`PUT /users/:id.json`

Client MUST be authenticated and can only update it's own user.

Parameters: all <<User>> data type parameters.

*Response*

Updated <<User>> structure.

=== Show User

`GET /users/:id.json`

*Response*

<<User>> structure.

=== Follow User

`POST /users/:id/follow.json`

Client MUST be authenticated and MUST NOT follow itself.

*Response*

Updated <<User>> structure of a followee.

=== Unfollow User

`POST /users/:id/unfollow.json`

Client MUST be authenticated and MUST NOT unfollow itself.

*Response*

Updated <<User>> structure of an unfollowee.

=== List followers

`GET /users/:id/followers.json`

Client MUST be authenticated.

*Response*

List of <<User>> structures of a followers.

=== List followees

`GET /users/:id/followees.json`

Client MUST be authenticated.

*Response*

List of <<User>> structures of a followees.

=== Create Post

`POST /posts.json`

Client MUST be authenticated.

Parameters: <<Post>> data type parameters namespaced with `post`.

*Response*

<<Post>> structure.

=== List Posts

`GET /posts.json`

*Response*

List of <<Post>> structures.

=== List Posts of a user

`GET /users/:user_id/posts.json`

*Response*

List of <<Post>> structures.

=== Like Post

`POST /posts/:id/like.json`

Client MUST be authenticated.

*Response*

Updated <<Post>> structure.

=== Unlike Post

`POST /posts/:id/unlike.json`

Client MUST be authenticated.

*Response*

Updated <<Post>> structure.

== Data types

=== User

[%header,cols="1%,1%,98%"]
|===
|Attribute name |Type |Description

|id
|Integer
|Identificator of a user

|email
|String
|Email address

|full_name
|String?
|User name

|bio
|String?
|Biography

|portrait
|String
|Userpic URL

|posts_count
|Integer
|Total number of user's posts

|followers_count
|Integer
|Total number of user's followers

|followees_count
|Integer
|Total number of user's followees

|is_follower
|Boolean
|Is this user a follower of the current user?

|is_followee
|Boolean
|Is this user a followee of the current user?
|===

=== Post

[%header,cols="1%,1%,98%"]
|===
|Attribute name |Type |Description

|id
|Integer
|Identificator of a post

|location
|String?
|Location (example: "New York Central Park")

|description
|String?
|First post comment of post creator

|image
|String
|Post image URL

|user
|<<User>>
|Creator of post structure

|likes_count
|Integer
|Total number of likes for this post

|liked
|Boolean
|Was this post liked by current user?

|created_at
|Integer
|UNIX timestamp of Post creation
|===
